name: 'React Native Android CI'

on:
  push:
    branches: [ feat/react-native ]
  pull_request:
    branches: [ feat/react-native ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Enable Long Paths
      shell: powershell
      run: |
        New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `  -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force

    - name: 'Checkout code'
      uses: actions/checkout@v3

    - name: Ensure Ninja >= 1.12
      run: |
        powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -File .github/scripts/ensure-ninja.ps1
      shell: bash

    - name: 'Run wash.bash'
      run: |
        ./scripts/wash.bash
      shell: bash

    - name: 'Run rinse.bash'
      run: |
        ./scripts/rinse.bash
      shell: bash

    - name: 'Run repeat.bash'
      run: |
        ./scripts/repeat.bash
      shell: bash
